export default [
	{ name: "3DCG - /3/", value: "3", nsfw: false },
	{ name: "Anime & Manga - /a/", value: "a", nsfw: false },
	{ name: "Adult Cartoons - /aco/ 🔞", value: "aco", nsfw: true },
	{ name: "Advice - /adv/", value: "adv", nsfw: false },
	{ name: "Animals & Nature - /an/", value: "an", nsfw: false },
	{ name: "Random - /b/ 🔞", value: "b", nsfw: true },
	{ name: "International/Random - /bant/ 🔞", value: "bant", nsfw: true },
	{ name: "Business & Finance - /biz/", value: "biz", nsfw: false },
	{ name: "Anime/Cute - /c/", value: "c", nsfw: false },
	{ name: "Cosplay & EGL - /cgl/", value: "cgl", nsfw: false },
	{ name: "Food & Cooking - /ck/", value: "ck", nsfw: false },
	{ name: "Cute/Male - /cm/", value: "cm", nsfw: false },
	{ name: "Comics & Cartoons - /co/", value: "co", nsfw: false },
	{ name: "Hentai/Alternative - /d/ 🔞", value: "d", nsfw: true },
	{ name: "Do It Yourself - /diy/", value: "diy", nsfw: false },
	{ name: "Ecchi - /e/ 🔞", value: "e", nsfw: true },
	{ name: "Flash - /f/ 🔞", value: "f", nsfw: true },
	{ name: "Fashion - /fa/", value: "fa", nsfw: false },
	{ name: "Fitness - /fit/", value: "fit", nsfw: false },
	{ name: "Technology - /g/", value: "g", nsfw: false },
	{ name: "Graphic Design - /gd/", value: "gd", nsfw: false },
	{ name: "Adult GIF - /gif/ 🔞", value: "gif", nsfw: true },
	{ name: "Hentai - /h/ 🔞", value: "h", nsfw: true },
	{ name: "Hardcore - /hc/ 🔞", value: "hc", nsfw: true },
	{ name: "History & Humanities - /his/", value: "his", nsfw: false },
	{ name: "Handsome Men - /hm/ 🔞", value: "hm", nsfw: true },
	{ name: "High Resolution - /hr/ 🔞", value: "hr", nsfw: true },
	{ name: "Oekaki - /i/ 🔞", value: "i", nsfw: true },
	{ name: "Artwork/Critique - /ic/ 🔞", value: "ic", nsfw: true },
	{ name: "International - /int/", value: "int", nsfw: false },
	{ name: "Otaku Culture - /jp/", value: "jp", nsfw: false },
	{ name: "Weapons - /k/", value: "k", nsfw: false },
	{ name: "LGBT - /lgbt/", value: "lgbt", nsfw: false },
	{ name: "Literature - /lit/", value: "lit", nsfw: false },
	{ name: "Mecha - /m/", value: "m", nsfw: false },
	{ name: "Pony - /mlp/", value: "mlp", nsfw: false },
	{ name: "Music - /mu/", value: "mu", nsfw: false },
	{ name: "Transportation - /n/", value: "n", nsfw: false },
	{ name: "Current News - /news/", value: "news", nsfw: false },
	{ name: "Auto - /o/", value: "o", nsfw: false },
	{ name: "Outdoors - /out/", value: "out", nsfw: false },
	{ name: "Photography - /p/", value: "p", nsfw: false },
	{ name: "Papercraft & Origami - /po/", value: "po", nsfw: false },
	{ name: "Politically Incorrect - /pol/ 🔞", value: "pol", nsfw: true },
	{ name: "Professional Wrestling - /pw/", value: "pw", nsfw: false },
	{ name: "Question & Answer - /qa/", value: "qa", nsfw: false },
	{ name: "Quests - /qst/", value: "qst", nsfw: false },
	{ name: "Adult Requests - /r/ 🔞", value: "r", nsfw: true },
	{ name: "ROBOT9001 - /r9k/ 🔞", value: "r9k", nsfw: true },
	{ name: "Sexy Beautiful Women - /s/ 🔞", value: "s", nsfw: true },
	{ name: "Shit 4chan Says - /s4s/ 🔞", value: "s4s", nsfw: true },
	{ name: "Science & Math - /sci/", value: "sci", nsfw: false },
	{ name: "Cams & Meetups - /soc/ 🔞", value: "soc", nsfw: true },
	{ name: "Sports - /sp/", value: "sp", nsfw: false },
	{ name: "Torrents - /t/ 🔞", value: "t", nsfw: true },
	{ name: "Traditional Games - /tg/", value: "tg", nsfw: false },
	{ name: "Toys - /toy/", value: "toy", nsfw: false },
	{ name: "Off-Topic - /trash/ 🔞", value: "trash", nsfw: true },
	{ name: "Travel - /trv/", value: "trv", nsfw: false },
	{ name: "Television & Film - /tv/", value: "tv", nsfw: false },
	{ name: "Yuri - /u/ 🔞", value: "u", nsfw: true },
	{ name: "Video Games - /v/", value: "v", nsfw: false },
	{ name: "Video Game Generals - /vg/", value: "vg", nsfw: false },
	{ name: "Very Important Posts - /vip/", value: "vip", nsfw: false },
	{ name: "Video Games/Multiplayer - /vm/", value: "vm", nsfw: false },
	{ name: "Video Games/Mobile - /vmg/", value: "vmg", nsfw: false },
	{ name: "Pokémon - /vp/", value: "vp", nsfw: false },
	{ name: "Retro Games - /vr/", value: "vr", nsfw: false },
	{ name: "Video Games/RPG - /vrpg/", value: "vrpg", nsfw: false },
	{ name: "Video Games/Strategy - /vst/", value: "vst", nsfw: false },
	{ name: "Virtual YouTubers - /vt/", value: "vt", nsfw: false },
	{ name: "Anime/Wallpapers - /w/", value: "w", nsfw: false },
	{ name: "Wallpapers/General - /wg/ 🔞", value: "wg", nsfw: true },
	{ name: "Worksafe GIF - /wsg/", value: "wsg", nsfw: false },
	{ name: "Worksafe Requests - /wsr/", value: "wsr", nsfw: false },
	{ name: "Paranormal - /x/", value: "x", nsfw: false },
	{ name: "Extreme Sports - /xs/", value: "xs", nsfw: false },
	{ name: "Yaoi - /y/ 🔞", value: "y", nsfw: true },
];
